Repository 5kdk/QnA-Box, pull requests merged in 2023-08, with the labels that each got.

#8 Chore/more project init settings/5kdk
  package-lock.json
  package.json
  src/components/atom/Flex.tsx
  src/styles/GlobalStyle.tsx
  tsconfig.json
  vite.config.ts
Labels: invalid

#14 Feat/make atoms/yunh7
  src/assets/images/loading.png
  src/components/atom/Button.tsx
  src/components/atom/Loading.tsx
  src/components/atom/Toggler.tsx
  src/components/atom/WideButton.tsx
  src/components/molecules/InfoModal.tsx
  src/components/molecules/Question.tsx
Labels: design

#25 Feat/user
  src/components/User/InfoSubject.tsx
  src/components/User/UserInfo.tsx
  src/components/molecules/Item.tsx
  src/components/molecules/Question.tsx
  src/components/pages/User.tsx
Labels: page

#27 Feat/account
  src/components/User/InfoSubject.tsx
  src/components/atom/Button.tsx
  src/components/pages/Account.tsx
  src/components/pages/EditAccount.tsx
  src/hooks/useImgFile.ts
  src/styles/buttonCss.ts
Labels: page

#29 Feat/error
  src/App.tsx
  src/components/pages/Error.tsx
Labels: page

#31 Feat/signin page/kyusung
  package-lock.json
  package.json
  src/assets/images/kakao_login.png
  src/components/atom/Note.tsx
  src/components/molecules/Input.tsx
  src/components/pages/Signin.tsx
  src/components/pages/Signup.tsx
Labels: page

#34 Refactor/common
  src/components/molecules/Input.tsx
  src/styles/GlobalStyle.tsx
Labels: design

#47 Feat/firebase auth/5kdk
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/molecules/SideNav/SideNav.tsx
  src/components/pages/Signin.tsx
  src/components/pages/Signup.tsx
  src/guards/AuthenticationGuard.tsx
  src/jotai/atom/userState.ts
  src/services/auth.ts
  src/services/config.ts
  src/services/firebase.ts
  src/utils/extractUsernameFromEmail.ts
Labels: api, feature

#50 fix: atom 오류 수정
  src/guards/AuthenticationGuard.tsx
  src/jotai/atom/userState.ts
Labels: bug

#62 Feat/firebase boxes and comments/5kdk
  src/constants/collectionNames.ts
  src/services/auth.ts
  src/services/boxes.ts
  src/services/comments.ts
Labels: api, feature

#67 Feat/yunh7
  src/App.tsx
  src/components/atom/Notification.tsx
  src/components/pages/Account.tsx
  src/components/pages/EditAccount.tsx
  src/components/pages/User.tsx
  src/hooks/useReqTryCatch.ts
  src/services/auth.ts
  src/services/comments.ts
  src/services/profile.ts
  src/styles/GlobalStyle.tsx
  src/utils/index.ts
  src/utils/reqTryCatch.ts
Labels: api

#68 Feat/box list page detail/5kdk
  package-lock.json
  package.json
  src/App.tsx
  src/components/BoxList/Board.tsx
  src/components/BoxList/BoxItem.tsx
  src/components/BoxList/Buttons.tsx
  src/components/BoxList/EditBox.tsx
  src/components/BoxList/index.ts
  src/components/atom/Filter.tsx
  src/components/atom/Loading.tsx
  src/components/molecules/BoxForm.tsx
  src/components/molecules/Controller.tsx
  src/components/molecules/ErrorFallback.tsx
  src/components/molecules/ItemSkeleton.tsx
  src/components/molecules/ItemWrapper.tsx
  src/components/molecules/index.ts
  src/components/pages/Box.tsx
  src/components/pages/BoxList.tsx
  src/components/pages/CreateBox.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/useGenericMutation.ts
  src/hooks/mutation/useRemoveMyBoxMutation.ts
  src/hooks/mutation/useUpdateMyBoxMutation.ts
  src/hooks/query/useMyListQuery.ts
  src/jotai/atom/filterState.ts
  src/jotai/atom/index.ts
  src/jotai/atom/searchInputState.ts
  src/jotai/atom/userState.ts
  src/services/boxes.ts
  src/services/profile.ts
  src/utils/localStorage.ts
Labels: feature

#74 fix: 다른 디바이스에서도 동기화 되도록 auth 로직 변경
  src/components/pages/Appshell.tsx
  src/components/pages/CreateBox.tsx
  src/components/pages/Signin.tsx
  src/jotai/atom/userState.ts
  src/services/auth.ts
  src/services/profile.ts
Labels: bug, api

#80 fix: revert 커밋
  src/components/pages/Appshell.tsx
  src/components/pages/CreateBox.tsx
  src/components/pages/Signin.tsx
  src/jotai/atom/userState.ts
  src/services/auth.ts
  src/services/profile.ts
Labels: bug

#81 Fix/obtimistic mutation bug/5kdk
  src/components/BoxList/Board.tsx
  src/components/BoxList/BoxItem.tsx
  src/components/BoxList/Buttons.tsx
  src/components/BoxList/EditBox.tsx
  src/components/atom/Edit.tsx
  src/components/molecules/BoxForm.tsx
  src/components/pages/BoxList.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/useGenericMutation.ts
  src/hooks/mutation/useRemoveMyBoxMutation.ts
  src/hooks/mutation/useUpdateMyBoxMutation.ts
  src/services/auth.ts
Labels: bug, feature

#83 Feat/root page/5kdk
  src/App.tsx
  src/assets/qa-logo-white.svg
  src/components/atom/Button.tsx
  src/components/atom/Logo.tsx
  src/components/atom/Text.tsx
  src/components/atom/Title.tsx
  src/components/atom/WideButton.tsx
  src/components/molecules/Header.tsx
  src/components/molecules/SideNav/SideNav.tsx
  src/pages/Root.tsx
  src/pages/Signin.tsx
  src/pages/index.ts
  src/styles/buttonCss.ts
Labels: page

#84 Refactor/side nav/5kdk
  src/components/atom/Note.tsx
  src/components/atom/WideButton.tsx
  src/components/molecules/CopyLight.tsx
  src/components/molecules/SideNav/BoxInfo.tsx
  src/components/molecules/SideNav/SideNav.tsx
  src/components/molecules/SideNav/UserInfo.tsx
  src/components/molecules/index.ts
  src/pages/Root.tsx
Labels: design

#88 Feat/pagenation and filtering/5kdk
  src/components/BoxList/Board.tsx
  src/components/BoxList/BoxItem.tsx
  src/components/BoxList/Buttons.tsx
  src/components/BoxList/Pagenation.tsx
  src/components/atom/Filter.tsx
  src/hooks/query/useMyListQuery.ts
  src/jotai/atom/filterState.ts
  src/pages/BoxList.tsx
Labels: feature

#113 Refactor/usability improvements/5kdk
  src/components/Box/BoxInfo.tsx
  src/components/Box/Comment.tsx
  src/components/Box/Comments.tsx
  src/components/Box/JoinOrExit.tsx
  src/components/BoxList/Board.tsx
  src/components/atom/Search.tsx
  src/components/molecules/SignForm.tsx
  src/pages/Signin.tsx
Labels: refactor

#120 Refactor/5kdk
  src/components/Box/BoxInfo.tsx
  src/components/Box/Comment.tsx
  src/components/Box/Comments.tsx
  src/components/Box/CreateContentBar.tsx
  src/components/BoxList/Board.tsx
  src/components/BoxList/BoxItem.tsx
  src/components/atom/Text.tsx
  src/components/molecules/CopyLight.tsx
  src/components/molecules/ErrorFallback.tsx
  src/hooks/mutation/index.ts
  src/hooks/mutation/useBoxMutation.ts
  src/hooks/mutation/useRemoveMyBoxMutation.ts
  src/hooks/mutation/useUpdateMyBoxMutation.ts
  src/pages/Appshell.tsx
Labels: refactor
